name: Build and Push Docker image

on:
  push:
    branches:
      - master  # ← 今 master でやってるなら master

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Log in to Docker Hub
      uses: docker/login-action@v3
      with:
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}

    - name: Build Docker image
      run: docker build -t ${{ secrets.DOCKER_USERNAME }}/tomcatserver:latest .

    - name: Push Docker image
      run: docker push ${{ secrets.DOCKER_USERNAME }}/tomcatserver:latest

    - name: Deploy to Oracle Cloud VM
      uses: appleboy/ssh-action@master
      with:
        host: ${{ secrets.SERVER_HOST }}
        username: opc
        key: ${{ secrets.SSH_PRIVATE_KEY }}
        script: |
          podman login docker.io -u ${{ secrets.DOCKER_USERNAME }} -p ${{ secrets.DOCKER_PASSWORD }}
          podman pull ${{ secrets.DOCKER_USERNAME }}/tomcatserver:latest
          podman stop tomcat-container || true
          podman rm tomcat-container || true
          podman run -d --name tomcat-container -p 8080:8080 ${{ secrets.DOCKER_USERNAME }}/tomcatserver:latest
